//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OnAddClickListener.java
//  @ Date : 2018/12/4
//  @ Author : hupei
//
//


package com.lyl.gridPictureViewLib;

import android.view.View;

/**
 * 添加图片回调接口
 */
public interface OnAddClickListener {
    /**
     * 添加图片接口
     */
    void onAddClick(View view, int position);
}
