//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OnDeleteClickListener.java
//  @ Date : 2018/12/4
//  @ Author : hupei
//
//


package com.lyl.gridPictureViewLib;

import android.view.View;

/**
 * 删除图片回调接口
 */
public interface OnDeleteClickListener {
    /**
     * 删除图片
     */
    void onDeleteClick(View view, int position,String picturePath);
}
