//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OnPictureClickListener.java
//  @ Date : 2018/12/4
//  @ Author : hupei
//
//

package com.lyl.gridPictureViewLib;


import android.view.View;

/**
 * 图片点击回调接口
 */
public interface OnPictureClickListener {
    /**
     * 回调接口
     */
    void onPictureClick(View view, int position);
}
