//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OnDeleteClickListener.java
//  @ Date : 2018/12/4
//  @ Author : hupei
//
//


package com.lyl.gridPictureViewLib.common;

import android.view.View;

/** */
public interface OnDeleteClickListener {
    /** */
    void onDeleteClick(View view, int position);
}
