//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OnPictureClickListener.java
//  @ Date : 2018/12/4
//  @ Author : hupei
//
//

package com.lyl.gridPictureViewLib.common;


import android.view.View;

/** */
public interface OnPictureClickListener {
    /** */
    void onPictureClick(View view, int position);
}
